### ISSUE TITLE
Fork for Extraordinary Form Calendar

### ISSUE THREAD

**Issue by agbloomfield** [romcal/romcal#51] opened 2018-07-10 19:15 UTC
I've just started working on a companion project to your (excellent development on RomCal), and would like to generate the 1962 Calendar -- the long-term project will include additional modules, but for now, I'm just trying to generate an Extraordinary Form option for RomCal itself.

**Comment by tukusejssirs** [comment] 2018-07-11 00:16
Hi, @agbloomfield!

I am very glad that a new contributor is at the horizon. ;)

Currently, the project ‘manager’, creator and owner, @pejulian is AWOL, actually for a few months now he haven’t done anyhing with `romcal` (at least not publicly) nor has given us any statement on this. I hope he has just some other duties he needs to tend to and will come back soon.

I am not a coder (just an amateur one); I contribute (mainly) to localisation and texual stuff.

I’ve already requested this feature (issue #23—I recommend you to read it as there I suggested how it should be done in my opinion) as historical calendar (or histcal for short), but this is twofold:
- firstly, the (General) Roman Calendar is divided according to the (main)changes throughout history, esp. in regards to the rules and the Calendar organisation, to multiple—let’s say—versions (one of these is the 1962 Calendar);
- secondly, whithin one particular Calendar version, there are some minor changes (like additions or removals of celebrations); these changes are mainly related to additions of new celebrations of recently canonised people.

Both of these parts of histcal would require start and end dates, between which the particular Calendar version or celebration is valid.

BTW, I’ve noticed you’ve made a commit in your fork to the `master` branch, which is equivalent to stable and old version and is not actively developed anymore. Currently developed (and current version) is the `romcal-es6`, as it is re-made from the ground up using ES6. Therefore, I strongly recommend to move your code to that branch.

Also, I recommend that after forking any project, you would create a copy of a branch you’d like to contribute to.

**Comment by tukusejssirs** [comment] 2018-07-11 00:39
And also I recommend you to read all the other open issues, as they contain some enhancements requests that might be (I hope they will be) coded into `romcal` and i think that all the codings (including histcal) should be coded with these enhancements in mind. I think you shoild read mainly these issues: #12, #18, #20, #23, #24, #26, #48, and partially #43. I suppose you’ve already read the `romcal-es6` [readme](https://github.com/pejulian/romcal/blob/romcal-es6/README.md).

**Comment by agbloomfield** [comment] 2018-07-11 11:16
Full confession: I hadn't had time to read the open issues -- I really just started poking about, and I'm not sure I even see the es6 branch.  And I'm rather new to using other GitHub repositories; this is a new project for me, but one I'm committed to developing as much as possible.

Thanks so much!

**Comment by tukusejssirs** [comment] 2018-07-11 13:23
PS (I am writing this at the end of this comment, but it should be read at the beginning)—I am replying to the first version of your comment; since you have modified, some parts are now irrevelant, but still I’ll post it for it take more time to edit. Thank you for understanding. :)

First thing you should do is to get accustomed with github.com and `git` in general.

## 1 Branch Selection
You can toggle between branches using your browser and github.com website; I believe the following image is quite versatile:

![How to toggle between branches](https://i.imgur.com/hdZN1mI.png)

I hope now you can see the `romcal-es6` branch.

## 2 Using `git`

### `git clone`

I have no idea how you commit to your branch currently, but the most effective way (in contrary to browser-based contributing) is using `git` client on your computer. You should search it on the web how you can install it, because it is OS-dependant (btw, on Linux, which I am using, it is much easier than on M$ WinDo$e). After you have installed it, you can use terminal (`cmd.exe` on M$ WinDo$e) the following to clone (copy/download) the `romcal-es6` branch from you forked `romcal`:

```bash
# Using HTTPS
git clone https://github.com/agbloomfield/romcal.git -b romcal-es6  # -b or --branch, it does not matter

# Using SSH (first you need to setup your `ssh` key pair; but using SSH is recommended by me)
git clone git@github.com:agbloomfield/romcal.git -b romcal-es6
```

This will create a new directory with the name of the cloned repo (in this example: `romcal`) in current working directory, unless there already exists such a non-empty directory (then it throws an error). You can clone it directly to a different directory / a directory with a different name with the directory (path and name) appending to the previous command, like this:

```
git clone git@github.com:agbloomfield/romcal.git -b romcal-es6 romcal-es6
```

This will clone `romcal-es6` branch from your `romcal` fork into `romcal-es6` directory.

Note that spaces are specially treated characters, therefore if you need to have a space in the directory name, you need to double-quote the dir name: `"romcal es6"`.

And using `git clone` only one branch is cloned. Maybe this is the reason you couldn’t see the `romcal-es6` branch. ;)

### Coding

First, as I already told you in different comment, you should create a new branch.

On github.com, open your `romcal` repo. Using branch selector, select `romcal-es6`. Then open the branch selector again and type the name of your new branch (make it descriptive, like `cal1962`) and press Enter (or click on `Create branch: {your_new_branch_name}`). You should check if below `Create branch: {ynbn}`, there is `from romcal-es6`—it is important to your the `romcal-es6` branch.

Now you can clone it to your computer (as described above; don’t forget to clone your newly create branch, not `romcal-es6`) and code. Any changes you currently make, are only on your computer. After you finished you current work on the code and with to commit it back to github.com, read on.

### `git add`
Before actual commit, you need to add the modified file you with to push (read: upload).

While you are in the cloned repo (`romcal` or `romcal-es6` from above), either in to repo root or one of its subdirs, you can run to following command to see the changed files:

```bash
git status
```

You can use it to see what files are modified, created or deleted. In red are those you have not added to commit and in green the ones that are to be commited.

After you have thought about which files to add, you can using the following command to actually add them to the upcoming commit:

```bash
git add file1 path1/file2 path2/* ...
```

You need to name them all if you have modified at least one file you want **not** to commit.

Or you can use the following command, you you with to commit **all* modified files:

```bash
git add --all
```

### `git commit`
The step will not push (upload) it to github.com yet, though it might look so.

I use the following command to add a commit message (description) to the commit; the commit message is required.

```bash
git commit -am "1962 Calendar"
```

### `git push`
This is the final step in pushing your commit to `github.com`. This will make it available online in your repo. It will push (upload) all your added (`git add`) files.

```bash
git push
```

## Pull requests
Though it can be done in terminal/cmd too, I create pull requests in the browser. While neither you are nor I am the original `pejulian/romcal` repo, we can only reate pull requests, but cannot merge them into the repo (see my [pull requests](https://github.com/pejulian/romcal/pulls?q=is%3Aopen+is%3Apr), which @pejulian had not yet merged).

The prerequisite is to have all files pushed to the correct branch.

In the image I have included in the beginning of this comment, on the right side of the branch selector, there is a button, New pull request. Click on it.

You’ll be redirected to a new page, where you can select the base repo/branch (your new branch from your repo) and the head ones (`pejulian/romcal-es6`). Compare the differences and if everything is alright, you can create your (probably) first push request. :)

**Comment by agbloomfield** [comment] 2018-07-11 14:55
Wow! That's even more tutorial than I needed, but all in one place.  Thank you so much.  I've started with git for awhile, but never used any other repositories.  I'll dig in.  Thanks!

**Comment by tukusejssirs** [comment] 2018-07-11 14:59
Anytimes! :)

Another confession: I myself am relatively new to `git`, I might know some details wrong. ;) … But the commands I use all the time, they are working as expected, but the process might require some additions to make it even better. :)

BTW, what’s your OS? :)

**Comment by agbloomfield** [comment] 2018-07-12 12:42
I've been working in c9.io for the last couple years (so Ubuntu, in that case), but have a Mac and PC on my desk (and a Chromebook), and always have access to Linux VMs.  And FreeBSD when necessary.

But my experience with `git` (so far) has just been following tutorials and making sure my own commits work with their notes, and then being able to deploy the code.

**Comment by tukusejssirs** [comment] 2019-02-12 18:20
@agbloomfield, if yo still wish to contribute, we need a list of all saints/blesseds and celebration names for the extraordinary cal. [Here](https://docs.google.com/spreadsheets/d/1c9YWtfntpxy0r0rg0mfowJ2v-yKW6wSMmNzyY3umBU4/edit?usp=drivesdk)’s what I did for `cal1962`. Note that itis still a work in progress.

Anyway, we need one combined list for all calendars, therefore it would be nice if you don’t add saints/blessed/celebations celebrated in `cal1962`, i.e. in the tables above.

**Comment by agbloomfield** [comment] 2019-02-12 18:53
@tukusejssirs That's terrific!  I'll start working on compiling the list.  Thanks!

**Comment by tukusejssirs** [comment] 2019-02-12 19:36
Btw, my list of `saints` is more or less finished, although:

- there are some duplicates;
- some columns might added or removed;
- some columns need to be filled yet.

In `celebrations`, have not done yet much and still I miss some/many.

Titles (like `martyr`, `protomartyr`, `patron of xxx`), canonisation level (blessed or saint) are listed in separate sheet in order make them translatable an then localisable (they are to receive key names as currently only the celebrations have).

I’ve just added some `shortcuts` to help you read the spreadsheet. :)

Companions are also translatable; in `saints` sheets. Strings to translate are in `companions` and list of celebration names that contain `companions` is in `companions_list` sheet.

**Comment by tukusejssirs** [comment] 2019-02-12 20:40
I was wrong about finishe list of `saints`. Actually I need to finish them from 602nd row onwards. I’m on right now. :)

**Comment by tukusejssirs** [comment] 2019-02-13 12:14
And my mistake: in this my comment, I wrote `cal1962`, while I meant `cal1969`, that is the New Order of Mass. I correct it. Other things a still valid. :)

**Comment by emagnier** [comment] 2019-12-10 22:32
This topic is a duplicate of #23. Please continue the discussion in this first topic for not to scatter.

**Closed by emagnier** 2019-12-10 22:32 UTC
Labels: duplicate, feature request
